# Generated by Django 5.1.7 on 2025-03-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0003_cliente_endereco_cliente_foto_cliente_telefone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='foto',
            field=models.SlugField(),
        ),
    ]
